new wallpapers
goatfiles/wallpapers pull request #8
Opened 2023-08-26 12:37 UTC by gitEugeneL

_Your wallpaper set is amazing! Thank you so much._
I thought I'd add some of the wallpapers I have.

2023-08-26 16:31 UTC, amtoine requested changes
> *Your wallpaper set is amazing! Thank you so much.*
>
thanks for the kind words :blush: 
happy you like it :yum: 

> I thought I'd add some of the wallpapers I have.
>
ooh yeah for sure, that's a good idea, let's share wallpapers :partying_face: 

i'd just move two of the wallpapers and then let's land this :wink:

2023-08-26 16:31 UTC, amtoine commented on wallpapers/other/0377_mountain-dreamscape.jpg
i would put that one in `wallpapers/real/`

2023-08-26 16:31 UTC, amtoine commented on wallpapers/other/0378_spectacular-evening-sky-illustration.jpg
i would put that one in `wallpapers/real/`

2023-08-27 15:32 UTC, gitEugeneL commented on wallpapers/other/0377_mountain-dreamscape.jpg
Yeah, of course I've already done that

2023-08-27 15:32 UTC, gitEugeneL commented on wallpapers/other/0378_spectacular-evening-sky-illustration.jpg
Yeah, of course I've already done that

2023-08-27 16:40 UTC, amtoine approved these changes
thanks for moving the files @gitEugeneL :pray: 

let's land this then :yum:

2023-08-27 16:40 UTC, merged